### ISSUE TITLE
create script to change plot and site names

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#104]
@ValentineHerr, I'd like a mechanism to change site and plot names throughout the database (SITES, PLOTS, MEASUREMENTS, HISTORY) whenever we identify a desired change. I have created a [spreadsheet to log these changes](https://github.com/forc-db/ForC/blob/master/database_manipulation_records/site_and_plot_name_changes.csv). Could you please create a script that can do this. I will soon add example (actual) changes to implement.

**Comment by ValentineHerr** [comment]
I have a script that does that. It requires to manually enter the "old name" and the "new name". 
Actually there is 2 scripts one for [column names](https://github.com/forc-db/ForC/blob/master/scripts/z_archive/Changing_column_names_in_data_metadata_and_scripts.R) and one fro [variables names](https://github.com/forc-db/ForC/blob/master/scripts/z_archive/Changing_variable_names_in_data_metadata_and_scripts.R) but I think they do pretty much the same thing and I should delete one.

I would have to test it once when you have a first example, to see if it does what is expected.

If the number of plot and site names to change is manageable, I think leaving the script with a manual entry might be a better option rather than trying to write a script that would read the CSV file and find which changes have not been made yet etc... It would allow to double check, one site at a time, that changes were applied correctly. What do you think?
