### ISSUE TITLE
Update ForC simplified

### ISSUE THREAD

**Issue by beckybanbury** [forc-db/ForC#171]
@ValentineHerr I'll be using the ForC simplified data in my analysis - I'm currently looking at sample sizes of different variables to plan the analysis, so it would be helpful to have the updated ForC simplified to work with. Is it okay for me to update using your script, or is this something you prefer to do yourself?

**Comment by ValentineHerr** [comment]
@beckybanbury,
I am still working on the duplicate records and a few other things. I feel that I am many steps away from getting it ready but maybe I should just go ahead and update the measurements with what I have so far. That will always be better than what the current version is.
There will be a few manual steps and you will probably be the best person to do them. Once you do those, you can update ForC simplified yourself.
I think I should be able to get that done today and I can post a specific issue for the steps you will have to do.

In the mean time, you can already update ForC simplified now (I think the code still works but let me know if it doesn't, there might be some issue with PLOTS column names), knowing it is not the best version yet, and start working on your scripts, both for looking at sample size (I don't think there will be major changes) and for your analysis. It will b easy to re-run them on the better version.

**Comment by beckybanbury** [comment]
@ValentineHerr thanks! I've got the code to work, but currently the code is excluding the data Abby and I entered because the "conflicts" column isn't coded. I presume this will be sorted once the duplicates code is run on that data, or is it a different code that I need to run?

**Comment by ValentineHerr** [comment]
FYI, I just updated PLOTS and saw that you had just done it too. I don't think that it will cause problems because it should basically be the same thing but I wanted to point it out just in case.

**Comment by ValentineHerr** [comment]
All right... This is not happening...
On line of code that takes 2 minutes to run at work is taking more than 3 hours now and is still not completed on my machine.
I tried to run it on the Rstudio Cloud (pretty cool thing by the way) hoping that the server would run it quickly but it does not. Maybe it is because my connection is no amazing...

So, @beckybanbury, please:

- [ ] run scripts\z_archive\Add_D.precedence.measurement.ID.R (you will have to install.packages("lubridate")) --> measurements should be updated --> commit the change in measurements with "add and assign D.precedence.measurement.ID"

- [ ] open scripts\z_archive\ID_sets_of_duplicate_records.R and run until line 143. If you get this line to be done in a few minutes, that is great... if not, please let me know. If it works, continue running the rest and let me know if you find it confusing. At the end you should get some pop up messages. You can ignore the first one. The second message should tell you that "There is 76 groups where D precedence needs to be given manually." If you don't get 76 (or close) let me know.

 - [ ] If things go smoothly above, run the last line that is commented out (write.csv(MEASUREMENTS.final, "data/ForC_measurements.csv", row.names = F)) to save the measurements --> commit  the change in measurements with "update conflict related columns automatically"

- [ ] Now you have to manually edit the D.precendence and D.precedence.measurement.ID of those D.groups that are unclear. you can see what the groups are by running again line 1484 to 1488. It will show them to you one by one, you have to press enter to go to the next one. You need to find those records by hand (in Excel) to decide what record gets precedence (probably the one you entered but it needs review). Once you picked what record is the best in one group, give it a "1" in D.precedence and give a "0" to the other records of the group. Then (very important) copy the measurement.ID of that record and paste it in D.precedence.measurement.ID for all the records of the group (including himself).

- [ ] save and commit your changes with "manually edit the D.precendence and D.precedence.measurement.ID "

- [ ] if all goes well, push and let me know yo are done. Next step for me is to update the script that reconcile the duplicates.

**Comment by beckybanbury** [comment]
@ValentineHerr I have managed to get the code to work and get a pop-up that says I have 76 groups where D precedence has to be given manually. However, I think there may be a problem with the sections of codes that read like this (lines 1468 and 1484):
for(split.ID in missing.D.precedence.split.ID) {
  X <- MEASUREMENTS.final[MEASUREMENTS.final$split.ID %in% split.ID & grepl("D", MEASUREMENTS.final$conflicts), ]
  print(X)
  readline()
}
From what you wrote above the whole script should run and then it is possible to go back and re-run these sections to see the groups. When I run these sections it's getting stuck + I have to manually press enter on the console to get it to run through. This means if I run the whole code, rather than line by line, it's getting stuck + not giving the right output beyond this point. I've managed to get it all to run by doing it line by line, but I'm guessing this is not ideal for the future?

**Comment by beckybanbury** [comment]
@ValentineHerr I've saved the ForC_measurements file and committed it to my branch because I think that in a few cases the code may have overwritten previously assigned D precedence. It would be great if you could review the changes and let me know!

**Comment by ValentineHerr** [comment]
@beckybanbury thank you so much for running the code. I am glad it worked on your machine.
You are right, "readline()" in line 1484 should be commented out by default so the code runs smoothly for someone who won't be looking at those 76 groups of duplicates one by one.


I will review those overwritten D precendence. Hopefully it happens only when I agreed it should, meaning for the following measurement.ID:
                                  "11525;11541", # Abby Ferson weird assignment of R group
                                  "11542;11543;11552;11560", # Abby Ferson weird assignment of R group
                                  "11576;19886;19887;19888", # Abby Ferson weird assignment of R group
                                  "11647;11652", # Abby Ferson weird assignment of R group
                                  "3229;3236;3239;12103",
                                  "3230;3237;3240;12104",
                                  "8816;17416;17480", # dat NA, start date 2012, 1992, en data 2012, 2012... 
                                  "3510;3511;3512;17378",
                                  "1684;1685",
                                  "15278;15279;15280;15281;15290;15291;15293;15294;15295"

I will keep you posted.

**Comment by ValentineHerr** [comment]
I pushed a code that will help comparing master version and your branch version (output of "ID_sets_of_duplicate_records.R") [here
](https://github.com/forc-db/ForC/blob/master/scripts/z_archive/compare_duplicate_records_btwn_master_version_of_MEASUREMENTS_and%20beckybanbury_version.R).
1. So there are a few D.precendence that have been changed because new entries (yours) came into play and are now part of previously existing D.groups. They are pretty complicated cases that my code does not handle well. You will have to review them by hand. Here are the 3 plots:

sites.sitename | plot.name | variable.name
-- | -- |--
Harvard Forest - Little Prospect Hill | EMS Tower (HFR1) | GPP_C
Le Bray | Managed 1970 pine plantation | GPP_C
Soroe | Managed | GPP_C

Keep what you find in a separate file because I'll be editing the code (see bellow) so you will have to do it again (you can also wait until I am done with task bellow). Make sure you enter conflict.notes adequatly (look at example of notes in the current measurement file)

2. There is some other issues that should be fixed in my code (D.groups "NAC" while there is a D.precedence). I think I know what is going on but I need to work on the code. For that I need your help @beckybanbury... Could you run  scripts\z_archive\ID_sets_of_duplicate_records.R again (on the master version of measurements, not the verion of your branch) until line 143 and then run:
`save(MEASUREMENTS.split, file = "scripts/z_archive/MEASUREMENTS.split.Rdata")`

commit and push that new file so that I can access it without having to run line 143.

Thanks !
Let me know if you have any questions!

**Comment by beckybanbury** [comment]
@ValentineHerr I'm having trouble pushing the MEASUREMENTS.split.Rdata file because it's so large (0.2 GB). Is there a different way to get you the information? I'll keep trying but GitHub desktop isn't doing well with it!

**Comment by ValentineHerr** [comment]
hmm... did you try to drag the file directly into GitHub online?
you can try ` saveRDS(MEASUREMENTS.split, file = "scripts/z_archive/MEASUREMENTS.split.rds")` and see if that is smaller

**Comment by bpbond** [comment]
For a file that large you probably want to set up [Git LFS](https://git-lfs.github.com).

**Comment by beckybanbury** [comment]
Thanks all - @ValentineHerr I've tried uploading the file as a release, saved [here](https://github.com/forc-db/ForC/releases/tag/v1) ; let me know if that's any use to you.

**Comment by ValentineHerr** [comment]
that is perfect! thank you so much!

**Comment by ValentineHerr** [comment]
@beckybanbury ,
The code was giving me errors (that I fixed) but it was related to a case of your recent edits of _D.precedence_. Sorry, I know it is pretty tedious and confusing when some records are assigned to multiple groups but could you review what I suggest in the second table and let me know if that is what you meant to enter?

current:

measurement.ID |stand.age| D.group | D.precedence | D.precedence.measurement.ID
--|--|--|--|--
2234 | 75 | 1471;1475 | NAC | NA
2235 | 77 | 1472;1476 | NAC | NA
2236 | 78 | 1473;1477 | NAC | NA
2256 | 73 | 1460 | 0 | NA
19902 | 74 | 1460 | 0 | 19912
19903 | 75 | 1460;1471 | 0 | 19913
19905 | 77 | 1460;1472 | 0 | 19915
19906 | 78 | 1460;1473 | 0 | 19916
19912 | 74 | 1460 | 1 | 19912
19913 | 75 | 1460;1475 | 1 | 19913
19915 | 77 | 1460;1476 | 1 | 19915
19916 | 78 | 1460;1477 | 1 | 19916



Here are some rules:

- Any record that is assigned one or more _D.group_ should have _D.precedence_ 0 or 1. It should never be "NAC" or "NA" unless all of the records of its D.group also are "NAC" (in that case that would mean that _D.precedence_ was never assigned and _D.precedence.measurement.ID_ should also be NA
- If any record in a _D.group_ is assigned _D.precedence_ 1, all other records of that group should be 0 and all records should get the _measurement.ID_ of that record in _D.precedence.measurement.ID_
- for records belonging to multiple groups, it doesn' matter how you procede as long as at the end, the records that should be kept for the analysis have 1 in _D,precedence_ and their own _measurement.ID_ in _D.precedence.measurement.ID_

I am thinking that maybe your records should look like the table below? let me know if that is not the case...

suggested:

measurement.ID |stand.age| D.group | D.precedence | D.precedence.measurement.ID
--|--|--|--|--
2234 | 75 | 1471;1475 | 0| 19913
2235 | 77 | 1472;1476 | 0| 19915
2236 | 78 | 1473;1477 | 0| 19916
2256 | 73 | 1460 | 0 | 19912
19902 | 74 | 1460 | 0 | 19912
19903 | 75 | 1460;1471 | 0 | 19913
19905 | 77 | 1460;1472 | 0 | 19915
19906 | 78 | 1460;1473 | 0 | 19916
19912 | 74 | 1460 | 1 | 19912
19913 | 75 | 1460;1475 | 1 | 19913
19915 | 77 | 1460;1476 | 1 | 19915
19916 | 78 | 1460;1477 | 1 | 19916

Note: record 2256 with stand.age 73 is messing everything up because its date is 2000 to 2006 and most of other record fall in that intervall... that is why that D.group 1460 is covering so many records...

**Comment by beckybanbury** [comment]
@ValentineHerr yes, sorry for the confusion; I had a problem where I manually edited some of the groups but didn't complete editing them, and so had to return to it, so things are half finished. The script won't re-identify groups that need manually editing once they have a D group assigned, so I've been trying to work out a way of identifying which groups need editing. Because they have multiple groups it's a bit confusing, but hopefully I'll get there today! Your version is correct though!

**Comment by beckybanbury** [comment]
@ValentineHerr I've pushed the updated ForC measurements, which should now have all the entries that require manual editing completed. Please let me know if you have any problems with it!

**Comment by ValentineHerr** [comment]
@beckybanbury , thank you so much for working on that. Maybe the best step now would for you to run the script that identifies and groups the duplicates and to save the updated measurements in your branch so that I can again run some code to double check what happened …. What do You think?
Note that I pushed an update on that script this morning.

**Comment by beckybanbury** [comment]
@ValentineHerr do you mean to run the updated ID_sets_of_duplicate_records scripts on the updated measurements? When I am running it now I am not getting any changes to the measurements table and nothing flagged up in the script.

**Comment by ValentineHerr** [comment]
Hmm. Strange. Did you make sure to uncomment the row that saves the new measurements? Silly question but just to make sure.

**Comment by beckybanbury** [comment]
Embarrassingly no. I've re-run and pushed the output! I ran it twice and strangely got two different pop-ups each time; first time it said nothing to review, second time it said two groups needed review.

**Comment by ValentineHerr** [comment]
Interesting. Did you happen to look at those 2 groups?
I am going to compare your branch with the master version now. Sorry I am not super reactive these days.

**Comment by beckybanbury** [comment]
@ValentineHerr I re-ran the code and pushed it again - I'm getting some pretty strange outputs where it's overwriting large parts of the measurements table. I'm getting an error at row 110, but aside from that it's running okay.

**Comment by ValentineHerr** [comment]
@beckybanbury, there is 15381 NAs in _measurements.ID_ of your version of MEASUREMENTS. Do you know where they come from?

**Comment by beckybanbury** [comment]
@ValentineHerr I'm really unsure about this; in the script it looks like MEASUREMENTS.final possibly isn't getting written properly (it's all NAs), but I don't know why it's overwriting part but not all of MEASUREMENTS with NAs

**Comment by ValentineHerr** [comment]
@beckybanbury, I think I have to wait for the government shutdown to be over to work on that. I need a better working station that what I have at home. I am not going anywhere like this. Sorry. 
You should be able to work on the current ForC_simplified though, and get the code ready for your analysis. I know it is not ideal but I think it is the most effective for now... Let me know if you have any questions.

**Comment by beckybanbury** [comment]
@ValentineHerr  I've noticed that ForC_simplified is missing some of the data that has been flagged as an "s" conflict e.g. neither of the ANPP_woody_stem entries for Porce have been transferred. Is this because I need to manually assign precedence?

**Comment by ValentineHerr** [comment]
No, if a record is only a “s” conflict (meaning there is a number in _S.group_ and not in _D.group_) then there is no precedence to give and only the record with “s” will make it to ForC_simplied, records with “S” won’t.
Note that I am still working on the duplicate code so ForC will change soon.
