### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#46]
@teixeirak 
I will use this issue to ask you a few things that I need your input with

- [x] In HISTORY _percent.mortality_ there is 8 records with value "<<100%" and 184 with "<100%". I am ignoring them to calculate range  (in metadata) but I want to make sure you want to keep that (especially the "<<100%")
- [x] In HISTORY _plothistoryID.v1_ I get 5722 for the max and you had 2477. Is that normal ?
- [x] In metadata of HISTORY _levels_ I am replacing the range I find by NA, OK ?

- [x] In MEASUREMENTS _measurementID.v_, I get max = 17172 while yours is 4797. Is that normal ?
- [x] In MEASUREMENTS _dupcode_ there is 1 "d", should I replace by "D"?
- [x] In MEASUREMENTS _dupcode_ should D/DC, and DC/D be the change to be one or the other ?
- [x] In MEASUREMENTS _dupcode_ should D/M and M/D be the change to be one or the other ?

- [x] In metadata of PLOTS _year.establishment.oldest.trees_, why is range "-" and not "##-##" ?

- [x] Once all above is solved. Can I remove _range_ column of all metadata files and keep only Min and Max ?

- [x] Do we want to keep/rename column _indicates.site.that.lacks.info.direct.from.pub_ in SITES ? It does not appear in metadata

- [x] In paper. I get different number of variables than you. Are you looking at primary only and "merging" Carbon and Biomass into individual variables for the count ?
- [x] Can  we really compare the number of _geographic.area_ between new and old version since we are not using the same method ? I get 249 for tropical sites (apparently it was 178 before).
- [x]  I (and maybe the reader) need more guidance to fill (and maybe retrieve) the numbers in the following sentence : "Of the 2,731 plot records, 1,206 (44%) contain records of dates of establishment of the oldest cohort of trees, ## (#%) contain records of initiation of a post-disturbance cohort, ## (#%) contain records for one or more major disturbances, ## (#%) contain records for one or more non-stand clearing disturbances, and ## (#%) contain records for one or more management events."

**Comment by teixeirak** [comment]
**Please leave these**

In HISTORY plothistoryID.v1 I get 5722 for the max and you had 2477. Is that normal ?

**I think what happened here is that your number refers to the entire version 1, whereas mine refers to only TropForC-db (the published component). Stick with yours.**

In metadata of HISTORY levels I am replacing the range I find by NA, OK ?

**I'm not sure I understand this question. But on a related note, for all metadata files, please replace range with min, max, and mean (as in sites metadata).***

In MEASUREMENTS measurementID.v, I get max = 17172 while yours is 4797. Is that normal ?

**I think what happened here (and above) is that your number refers to the entire version 1, whereas mine refers to only TropForC-db (the published component). Stick with yours.**

In MEASUREMENTS dupcode there is 1 "d", should I replace by "D"?

**yes**

In MEASUREMENTS dupcode should D/DC, and DC/D be the change to be one or the other ?

**yes. either is fine**

In MEASUREMENTS dupcode should D/M and M/D be the change to be one or the other ?

**yes. either is fine**

In metadata of PLOTS year.establishment.oldest.trees, why is range "-" and not "##-##" ?

**my mistake**

Once all above is solved. Can I remove range column of all metadata files and keep only Min and Max ?

**Yes, please do**

Do we want to keep/rename column indicates.site.that.lacks.info.direct.from.pub in SITES ? It does not appear in metadata

**no, I'll delete it for pub version**

In paper. I get different number of variables than you. Are you looking at primary only and "merging" Carbon and Biomass into individual variables for the count ?

**yes, primary only. There's one part of the text where I merge them, but they are separate in the number presented in the abstract"**

Can we really compare the number of geographic.area between new and old version since we are not using the same method ? I get 249 for tropical sites (apparently it was 178 before).

**It's not exactly comparable, but should be close. There's a bunch of tropical data that wasn't published in the first version. To double check, you could see how many you get counting only the sites published in the first version (<=503)**

I (and maybe the reader) need more guidance to fill (and maybe retrieve) the numbers in the following sentence : "Of the 2,731 plot records, 1,206 (44%) contain records of dates of establishment of the oldest cohort of trees, ## (#%) contain records of initiation of a post-disturbance cohort, ## (#%) contain records for one or more major disturbances, ## (#%) contain records for one or more non-stand clearing disturbances, and ## (#%) contain records for one or more management events."

**I will fill this in (and also try to clarify for the reader).**

**Comment by ValentineHerr** [comment]
Indeed I get 248 geographic areas records published in first version and 580 new ones.

Also,  do we want a range of _establishment.ID_ in metadata of PLOTS ? or should I keep "-"

**Comment by teixeirak** [comment]
Let's delete reference to the old number of plots.

**Comment by teixeirak** [comment]
Please remove range for all metadata files, and replace with min, max, and mean. Does that get at your question? (I'm not sure I understand.)

**Comment by ValentineHerr** [comment]
Sorry it was not clear. I am asking if it is relevant to calculate the Min and Max of establishment.ID or if I should keep it blank.

**Comment by ValentineHerr** [comment]
Do you mean the reference of number of geographic.area in the paper when you say "delete reference to the old number of plots." ?

**Comment by teixeirak** [comment]
Yes, please do include those. They are relatively meaningless, but should be included as part of the metadata standards.

On Dec 14, 2017, at 3:38 PM, ValentineHerr <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean the reference of number of geographic.area in the paper when you say "delete reference to the old number of plots." ?
