### ISSUE TITLE
Variables with no range because no data

### ISSUE THREAD

**Issue by ValentineHerr** [forc-db/ForC#48]
@teixeirak would you like to fill in the range for the variables that are not used in MEASUREMENTS but that might be added in the future ? This would be so that they are not flagged  when someone enters new records.

If you wan to do that you can do it here and I can add it myself in the VARIABLES file

Here is the list of variables I am talking about:

- NPP_4
- NPP_5
- NPP_understory
- NPP_woody
- ANPP_litterfall_2_C
- ANPP_litterfall_3_C
- trees(0)_or_stems(1)

**Comment by teixeirak** [comment]
Please leave these as NA. It will be okay for them to be flagged. Flagging is just a warning that the values fall outside the current scope of the database, not an indication that they are necessarily wrong.

trees(0)_or_stems(1) is not a primary variable, it is a covariate. I noticed that its min and max were listed as NA in the variables table, and I think that's because you had it mis-classified.
