### ISSUE TITLE
Variable cleanup

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#53]
@ValentineHerr, I modified variable names and ordering according to some conventions that developed (see docs [here](https://github.com/forc-db/ForC_private/tree/master/variable%20name%20cleanup)). I'd like your help updating the master branch with these names. 

- [x] First, please review the [variable name conventions](https://github.com/forc-db/ForC_private/blob/master/variable%20name%20cleanup/Variable%20name%20conventions.docx) for compliance with database best practices. Let me know if there's anything you think we should change. 

- [x] Update ForC_variables: I  made changes in several fields, so please use [this file](https://github.com/forc-db/ForC_private/blob/master/variable%20name%20cleanup/ForC_variables_revamp.csv) as the new master, but first delete the field with old variable names. You'll also need to update variable names throughout the document, specifically in the equations, associate covariates, and notes fields.

- [x] Update ForC_measurements: update both variable names and associated covariate names

- [x] Update metadata and entity relationship diagram: changes include new field in ForC_variables (id number) and changes to categorical variables in variable.type ("primary" is replaced with "stock" and "flux)

**Comment by bpbond** [comment]
Out of curiosity, why does the end of the list (104-117) shift to using a dot convention (`N.mineralization`) instead of underscore (`soil_C`)?

**Comment by teixeirak** [comment]
I'm going with the convention of separating words with dots and modifiers with underscores. In that context, does it make sense to you?

**Comment by bpbond** [comment]
Ah. Sure. Almost _any_ convention is OK, as long as it's consistent, I think. Thanks for clarifying!

**Comment by ValentineHerr** [comment]
List and order of steps to do for this issue (for myself):

- [ ] Copy ForC_variables_revamp in ForC (from ForC_private)
- [ ] Delete ForC_variables from ForC
- [ ] Rename ForC_variables_revamp as ForC_variables
- [ ] Copy variables.name_OLD and variable.name columns in a separate txt file and save as ForC/metadata/archive/variable_names_polishing.txt
- [ ] Delete variables.name_OLD column in ForC_variables
- [ ] Create and save similar script as ForC/scripts/z_archive/Changing_column_names_in_data_metadata_and_script.R (probably can use the exact same)
- [ ] Commit changes so that it is easier to keep track of variable names change in the next step
- [ ] Working one variable name at a time, run the script, check changes, commit if all is good (keep note of what changes to manually revert, if any, in the txt file (on the line of the corresponding variable name)
- [ ] Push all commits

**Comment by ValentineHerr** [comment]
@teixeirak , il line 53 of [this file](https://github.com/forc-db/ForC_private/blob/master/variable%20name%20cleanup/ForC_variables_revamp.csv#L53) correct ?

It says old name is "BNPP_coarse _root" and new name is "BNPP_root_fine_C"

**Comment by teixeirak** [comment]
Ack! Thanks for catching that mistake.

**Comment by ValentineHerr** [comment]
Also, Is folieage_pN supposed to be foliage_pN ?

**Comment by teixeirak** [comment]
Yes. Thanks for catching my typos!
