### ISSUE TITLE
Re-run database consistency checks, metadata tables, figures, and stats in text

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#61]
@ValentineHerr,

Quite a few records have been removed from the database (issue #59). We'll need to re-run:
- [x] the database checks (some plots and sites may go)
- [x] the numbers in the metadata tables
- [x] figures
- [x] statistics for the text. 

Could you please work through as much of this as possible before your time off, in that order?

**Comment by ValentineHerr** [comment]
I noticed that "variables.name" is spelled inconsistently between tables: spelled without an s in VARIABLES table and metadata (as well as variable.type.. etc)

The metadata column names have been changed because R automatically replace spaces by period.


I don't have time to finish editing the numbers in the text. I wrote a comment where I stopped. I hope the rest can be done without me. Let me know if not and I can find some time during the week to do it.

**Comment by teixeirak** [comment]
I have fixed the variable.name problem.
