### ISSUE TITLE
Review/fix assignment of dup.nums 

### ISSUE THREAD

**Issue by teixeirak** [forc-db/ForC#74]
This is related it issues #68, #73  
Two issues:
- [ ] Reviewing records for Soroe, it appears that newer studies were not always assigned higher priority. Fixing this needs to be automated. 
- [ ] Yu_2014_hcdu averaged flux records across years. These duplicate other records, but these should be ignored when annual estimates are available for each year.

@ValentineHerr, can we write a script to fix these?

**Comment by ValentineHerr** [comment]
It is unclear to me why Yu_2014_hcdu, sometimes gets a "D" in _dup.code_ and sometimes not.
For example: _measurement.ID_ 8166 at Le Bray: NEE_C in 2003 is "D" but  _measurement.ID_ 8172 in 1997-2007 does not have a "D". There is no other record in 2003 that could explain why 8166 gets a "D".
I am guessing that part of the answer is because record 8172 includes 2007, a year with no other record. But does that mean we keep 8172 as an individual record ? If yes, 8166 should stand on its own too and not get a "D".

About Soroe, I thought the priority numbers were given by hand. I am happy to try to automate that but should I try to do it for all records then ?


On another note: 
I am confused about the difference between R and D in _dup.code_. 
For example, records 45, 46 and 47 are "R" but do have a different mean. Also they don't seem to differ in methodologie nor in year of citation but they do get ranked differently in _dup.num_ (while, if i understood well, they should get same rank, to be averaged).
Records 7988 and 7990 seem to be in the exact same situation as 45, 46 and 47 but they get a "D" in _dup.code_.

**Comment by teixeirak** [comment]
This issue is replaced by issue #76.
